sudo: required

services:
  - docker

# Omit running tests on temporal branches
branches:
  except:
    - /^tmp/

language: ruby
ruby:
  - "2.3.1"

before_install:
  - travis_retry ./test/before_install_setup

install:
  - travis_retry ./test/before_install_build

script:
  - ./test/script
